version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  tweetfetcher:
    environment:
      - "PYTHONUNBUFFERED=1"
    build: .
    image: tweetfetcher:${TAG:-latest}
    volumes:
      - .:/src
    build:
      context: .
      dockerfile: Dockerfile-Tweetfetcher
    depends_on:
      - rabbitmq
volumes:
  esdata1:
    driver: local