FROM golang:1.6.1-alpine

ADD . /app
WORKDIR /app

RUN go get github.com/go-martini/martini && \
    go get github.com/martini-contrib/render && \
    go get gopkg.in/mgo.v2 && \
    go get github.com/martini-contrib/binding