FROM golang:1.8

COPY . /
WORKDIR /src/searchservice

ENV PTCFRONTEND /react-frontend/build
ENV GOPATH=/
RUN go get gopkg.in/olivere/elastic.v5
RUN go get github.com/gorilla/context
RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/justinas/alice
RUN go build -o main .


EXPOSE 8080
CMD ["./main"]
