version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: sebp/elk
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms700m -Xmx700m"

  tweetfetcher:
    environment:
      - "PYTHONUNBUFFERED=1"
    build:
      context: .
      dockerfile: Dockerfile-Tweetfetcher
    depends_on:
      - rabbitmq
  tweetindexer:
    build:
      context: .
      dockerfile: Dockerfile-Tweetindexer
    depends_on:
      - rabbitmq
      - elasticsearch
  searchservice:
    build:
      context: .
      dockerfile: Dockerfile-Searchservice
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch